create table Team (
    id int primary key generated by default as identity,
    name varchar not null,
    country varchar not null,
    elo float
);

create table Probability (
    id int primary key generated by default as identity,
    home_team_win float,
    draw float
);

create table Match (
    id int primary key generated by default as identity,
    date date,
    league varchar,
    home_team_id int not null references Team(id) on delete set null,
    away_team_id int not null references Team(id) on delete set null,
    probability_id int not null references Probability(id) on delete set null
);