create table users (
    id int primary key generated by default as identity,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) check (role in ('ROLE_USER','ROLE_ADMIN')),
    favourite_team_id int not null references Team(id) on delete set null
)